/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as CardRouteImport } from './routes/card'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as RoundsNewRouteImport } from './routes/rounds.new'
import { Route as CoursesCourseIdEditRouteImport } from './routes/courses.$courseId.edit'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsNewRoute = RoundsNewRouteImport.update({
  id: '/rounds/new',
  path: '/rounds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdEditRoute = CoursesCourseIdEditRouteImport.update({
  id: '/courses/$courseId/edit',
  path: '/courses/$courseId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/rounds/new': typeof RoundsNewRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/rounds/new': typeof RoundsNewRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/rounds/new': typeof RoundsNewRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/edit': typeof CoursesCourseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/card'
    | '/play'
    | '/profile'
    | '/progress'
    | '/rounds/new'
    | '/courses/'
    | '/courses/$courseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/card'
    | '/play'
    | '/profile'
    | '/progress'
    | '/rounds/new'
    | '/courses'
    | '/courses/$courseId/edit'
  id:
    | '__root__'
    | '/'
    | '/card'
    | '/play'
    | '/profile'
    | '/progress'
    | '/rounds/new'
    | '/courses/'
    | '/courses/$courseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardRoute: typeof CardRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RoundsNewRoute: typeof RoundsNewRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesCourseIdEditRoute: typeof CoursesCourseIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds/new': {
      id: '/rounds/new'
      path: '/rounds/new'
      fullPath: '/rounds/new'
      preLoaderRoute: typeof RoundsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/edit': {
      id: '/courses/$courseId/edit'
      path: '/courses/$courseId/edit'
      fullPath: '/courses/$courseId/edit'
      preLoaderRoute: typeof CoursesCourseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardRoute: CardRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RoundsNewRoute: RoundsNewRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesCourseIdEditRoute: CoursesCourseIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
